allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  '@tailwindcss/oxide': false
  sharp: false
  unrs-resolver: false
  overrides:
  baseline-browser-mapping: $baseline-browser-mapping
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
  
